# Generated by Django 3.1.6 on 2021-02-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=32)),
                ('jumlah_pesanan', models.CharField(max_length=16)),
                ('proses', models.BooleanField(default=False)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.barang')),
            ],
        ),
        migrations.CreateModel(
            name='Produksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_produksi', models.CharField(max_length=16)),
                ('lead_time', models.CharField(max_length=4)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.barang')),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pemesanan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengambilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengambil', models.CharField(max_length=32)),
                ('jumlah_pengambilan', models.CharField(max_length=16)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.barang')),
            ],
        ),
    ]
