# Generated by Django 3.1.6 on 2021-02-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210206_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pegawai',
            old_name='id_bagian',
            new_name='bagian',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
