# Generated by Django 3.1.6 on 2021-02-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210206_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='bagian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bagian'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.barang'),
        ),
        migrations.AlterField(
            model_name='pengambilan',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.barang'),
        ),
        migrations.AlterField(
            model_name='produksi',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.barang'),
        ),
        migrations.AlterField(
            model_name='produksi',
            name='pesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pemesanan'),
        ),
    ]
