# Generated by Django 3.1.6 on 2021-02-06 05:57

import random
import logging
l = logging.getLogger('django.db.backends')
l = logging.getLogger('django.db.backends')
l.addHandler(logging.StreamHandler())
from django.db import migrations

def rand_name_gen():
    rand_idx = random.randint(0, 9)
    return ['Budi', 'Dedi', 'Dodi', 'Tim', 'Tom', 'Jerry', 'Boy', 'Timmy', 'Steven', 'Steve'][rand_idx]

def create_barang_pesanan_entries(apps, schema_editor):
    barang_model = apps.get_model("core", "barang")
    pemesanan_model = apps.get_model("core", "pemesanan")
    produksi_model = apps.get_model("core", "produksi")

    barang_list = [
        'iPhone',
        'iPhone 3G',
        'iPhone 3GS',
        'iPhone 4',
        'iPhone 4S',
        'iPhone 5',
        'iPhone 5c',
        'iPhone 5s',
        'iPhone 6',
        'iPhone 6 Plus',
        'iPhone 6s',
        'iPhone 6s Plus',
        'iPhone SE (1st generation)',
        'iPhone 7',
        'iPhone 7 Plus',
        'iPhone 8',
        'iPhone 8 Plus',
        'iPhone X',
        'iPhone XR',
        'iPhone XS',
        'iPhone XS Max',
        'iPhone 11',
        'iPhone 11 Pro',
        'iPhone 11 Pro Max',
        'iPhone SE (2nd generation)',
        'iPhone 12 mini',
        'iPhone 12',
        'iPhone 12 Pro',
        'iPhone 12 Pro Max',
    ]

    for nama_barang in barang_list:
        barang_obj = barang_model.objects.create(
            nama_barang=nama_barang
        )

        rand_pemesanan = random.randint(1, 12)
        for idx in range(rand_pemesanan):
            rand_name = rand_name_gen()
            rand_order_no = random.randint(5, 30)

            pemesanan_obj = pemesanan_model.objects.create(
                nama_pemesan=rand_name,
                barang=barang_obj,
                jumlah_pesanan=rand_order_no
            )

            rand_prod_no = random.randint(1, rand_order_no)
            rand_lead_time = random.randint(3, 7)
            produksi_obj = produksi_model.objects.create(
                pesanan=pemesanan_obj,
                barang=barang_obj,
                jumlah_produksi=rand_prod_no,
                lead_time=rand_lead_time
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210206_1232'),
    ]

    operations = [
        migrations.RunPython(create_barang_pesanan_entries)
    ]
